version: '3.8'
services:
 postgres:
  container_name: postgres-microservice
  image: postgres
  restart: always
  environment:
   POSTGRES_USER: "microservice"
   POSTGRES_PASSWORD: "microservice"
   APP_DB_USER: "docker"
   APP_DB_PASS: "docker"
   APP_DB_NAME: "docker"
  ports:
   - "5432:5432"
  volumes:
   - ./bd_init:/docker-entrypoint-initdb.d/
  networks:
   - microservice-network
 pgadmin:
  container_name: pgadmin-microservice
  image: dpage/pgadmin4
  restart: always
  environment:
   PGADMIN_DEFAULT_EMAIL: "admin@microservices.com.br"
   PGADMIN_DEFAULT_PASSWORD: "microservice"
  ports:
   - "15432:80"
  networks:
   - microservice-network
networks:
 microservice-network:
  driver: bridge
